export const moves = [
    {
        id: "default",
        title: "Default Move",
        outcomes: [
            "You fail.",
            "You fail.",
            "You fail, taking a consequence.",
            "You fail, taking a consequence.",
            "You succeed.",
            "You succeed.",
        ],
        lastNegative: 4,
    },
    {
        id: "negotiation",
        title: "Negotiation",
        outcomes: [
            "Negotiations fail. Violence begins.",
            "Negotiations fail. Parties offended.",
            "Negotiations fail, but a back door opens.",
            "Negotiations succeed, begrudgingly.",
            "Negotiations succeed with a friendship opportunity.",
            "Negotiations succeed and an alliance begins.",
        ],
        lastNegative: 3,
    },
    {
        id: "physical-combat",
        title: "Physical Combat",
        outcomes: [
            "Your attack misses, and you are _hurt_.",
            "Your attack misses, and you are _stunned_.",
            "You _hurt_ the target, but you are also _hurt_.",
            "You _hurt_ the target, and the target flees.",
            "You _hurt_ the target.",
            "You _hurt_ the target, who surrenders.",
        ],
        lastNegative: 3,
    },
    {
        id: "ace-pilot",
        title: "Ace Pilot",
        outcomes: [
            "Your craft goes careening out of control.",
            "No change, but a complication occurs.",
            "No change, but a complication occurs.",
            "Your maneuver succeeds, but a complication occurs.",
            "Your maneuver succeeds.",
            "Your maneuver succeeds beyond your expectations.",
        ],
        lastNegative: 3,
    },
    {
        id: "blaster-master",
        title: "Blaster Master",
        outcomes: [
            "Your attack misses, and the target gets away.",
            "You _hurt_ the target, and you are _hurt_.",
            "You _hurt_ the target, and you are _hurt_.",
            "You _hurt_ the target.",
            "You _hurt_ and stun the target.",
            "You _hurt_ the target, who surrenders.",
        ],
        lastNegative: 3,
    },
    {
        id: "engineer",
        title: "Engineer",
        outcomes: [
            "You fail, and something explodes.",
            "You fail, and something gets jammed.",
            "You fail, and something goes wrong.",
            "You succeed, but something else goes wrong.",
            "You succeed.",
            "You succeed, and what you're wroking on works better than before.",
        ],
        lastNegative: 3,
    },
    {
        id: "medic",
        title: "Medic",
        outcomes: [
            "The target takes 1 extra _hurt_.",
            "The target is now _stunned_.",
            "No effect.",
            "The target clears 1 _hurt_.",
            "The target clears 1 _hurt_.",
            "The target clears 1 _hurt_ and 1 other condition of your choice.",
        ],
        lastNegative: 3,
    },
    {
        id: "infiltrator",
        title: "Infiltrator",
        outcomes: [
            "You cannot enter, and enemies are alerted to your presence.",
            "You cannot enter, and enemies are alerted to your presence.",
            "You cannot enter, and you are _distracted_ for the next 2 turns.",
            "You can enter, but enemies are alerted to your presence.",
            "You can enter.",
            "You can enter, and you learn a new secret.",
        ],
        lastNegative: 3,
    },
    {
        id: "learner-of-secrets",
        title: "Learner of Secrets",
        description: "You may use this skill in research, physical investigation, conversation, or interrogation.",
        outcomes: [
            "You are _distracted_ for the next 2 turns.",
            "You learn nothing.",
            "You get a general sense of what you want to know, and you are distracted for the next 2 turns.",
            "You get a general sense of what you want to know.",
            "You learn everything you want to know.",
            "You learn everything you want to know, and a surprising truth.",
        ],
        lastNegative: 3,
    },
    {
        id: "master-manipulator",
        title: "Master Manipulator",
        outcomes: [
            "They refuse. Violence begins.",
            "They refuse. Parties offended.",
            "They'll do it for a price.",
            "They'll do it.",
            "They'll do it.",
            "They'll do it, and more besides.",
        ],
        lastNegative: 4,
    },
    {
        id: "psychic-scanner",
        title: "Psychic Scanner",
        outcomes: [
            "Psychic backlash; you are _hurt_.",
            "Learn the target's biggest secret.",
            "Learn the target's biggest weakness.",
            "Learn the target's biggest fear.",
            "Learn what the target's actually about to do.",
            "Learn how the target can be controlled.",
        ],
        lastNegative: 1,
    },
    {
        id: "survivalist",
        title: "Survivalist",
        outcomes: [
            "You lose your way and stumble into danger.",
            "You step in the wrong nest and take a random condition.",
            "You waste precious time, causing a lurking danger to manifest.",
            "You find a path, speeding up your progress.",
            "You find a helpful remedy. Heal 1 hurt on yourself or an ally.",
            "You learn an important secret about the environment.",
        ],
        lastNegative: 3,
    },
    {
        id: "telekinesis",
        title: "Telekinesis",
        outcomes: [
            "Psychic backlash; you are _hurt_.",
            "Nothing happens, and you are _distracted_ next turn.",
            "You partially succeed (_e.g._, you move something half the desired distance).",
            "You succeed, but you are _stunned_ next turn.",
            "You succeed.",
            "You succeed and can either sustain this for another turn or double its effect (your choice).",
        ],
        lastNegative: 2,
    },
    {
        id: "trap-expert",
        title: "Trap Expert",
        outcomes: [
            "The trap explodes. You are _hurt_, and so is another nearby person (choose randomly).",
            "The trap explodes. You are _hurt_.",
            "You disarm the trap, but you are _hurt_.",
            "You find and disable the trap.",
            "You find and disable the trap, learning a secret about how it was made.",
            "You find and disable the trap, and can safely take it with you and use it later.",
        ],
        lastNegative: 3,
    },
    {
        id: "wild-courage",
        title: "Wild Courage",
        outcomes: [
            "You fail and suffer a serious setback.",
            "You fail and suffer a significant setback.",
            "You fail.",
            "You succeed.",
            "You succeed even more than you anticipated.",
            "You succeed beyond your wildest expectations.",
        ],
        lastNegative: 3,
    },
];

export default moves;