export const moves = [
    {
        id: "default",
        title: "Default Move",
        outcomes: [
            "You fail.",
            "You fail.",
            "You fail, taking a consequence.",
            "You fail, taking a consequence.",
            "You succeed.",
            "You succeed.",
        ],
        lastNegative: 4,
    },
    {
        id: "negotiation",
        title: "Negotiation",
        outcomes: [
            "Negotiations fail. Violence begins.",
            "Negotiations fail. Parties offended.",
            "Negotiations fail, but a back door opens.",
            "Negotiations succeed, begrudgingly.",
            "Negotiations succeed with a friendship opportunity.",
            "Negotiations succeed and an alliance begins.",
        ],
        lastNegative: 3,
    },
    {
        id: "physical-combat",
        title: "Physical Combat",
        outcomes: [
            "Your attack misses, and you are hurt.",
            "Your attack misses, and you are stunned.",
            "You hurt the target, but you are also hurt.",
            "You hurt the target, and the target flees.",
            "You hurt the target.",
            "You hurt the target, who surrenders.",
        ],
        lastNegative: 3,
    },
    {
        id: "ace-pilot",
        title: "Ace Pilot",
        outcomes: [
            "Your craft goes careening out of control.",
            "No change, but a complication occurs.",
            "No change, but a complication occurs.",
            "Your maneuver succeeds, but a complication occurs.",
            "Your maneuver succeeds.",
            "Your maneuver succeeds beyond your expectations.",
        ],
        lastNegative: 3,
    },
    {
        id: "blaster-master",
        title: "Blaster Master",
        outcomes: [
            "Your attack misses, and the target gets away.",
            "You hurt the target, and you are hurt.",
            "You hurt the target, and you are hurt.",
            "You hurt the target.",
            "You hurt and stun the target.",
            "You hurt the target, who surrenders.",
        ],
        lastNegative: 3,
    },
    {
        id: "engineer",
        title: "Engineer",
        outcomes: [
            "You fail, and something explodes.",
            "You fail, and something gets jammed.",
            "You fail, and something goes wrong.",
            "You succeed, but something else goes wrong.",
            "You succeed.",
            "You succeed, and what you're wroking on works better than before.",
        ],
        lastNegative: 3,
    },
    {
        id: "medic",
        title: "Medic",
        outcomes: [
            "The target takes 1 extra hurt.",
            "The target is now stunned.",
            "No effect.",
            "The target clears 1 hurt.",
            "The target clears 1 hurt.",
            "The target clears 1 hurt and 1 other condition of your choice.",
        ],
        lastNegative: 3,
    },
    {
        id: "infiltrator",
        title: "Infiltrator",
        outcomes: [
            "You cannot enter, and enemies are alerted to your presence.",
            "You cannot enter, and enemies are alerted to your presence.",
            "You cannot enter, and you are distracted for the next 2 turns.",
            "You can enter, but enemies are alerted to your presence.",
            "You can enter.",
            "You can enter, and you learn a new secret.",
        ],
        lastNegative: 3,
    },
    {
        id: "learner-of-secrets",
        title: "Learner of Secrets",
        description: "You may use this skill in research, physical investigation, conversation, or interrogation.",
        outcomes: [
            "You are distracted for the next 2 turns.",
            "You learn nothing.",
            "You get a general sense of what you want to know, and you are distracted for the next 2 turns.",
            "You get a general sense of what you want to know.",
            "You learn everything you want to know.",
            "You learn everything you want to know, and a surprising truth.",
        ],
        lastNegative: 3,
    },
];

export default moves;